// examples/user-management/expo-user-management/components/Account.tsx
import { useState, useEffect } from 'react'
import { skybase } from '../lib/skybase'
import { StyleSheet, View, Alert } from 'react-native'
import { Button, Input } from '@rneui/themed'
import { Session } from '@skybase/skybase-js'
import Avatar from './Avatar'

export default function Account({ session }: { session: Session }) {
  const [loading, setLoading] = useState(true)
  const [username, setUsername] = useState('')
  const [website, setWebsite] = useState('')
  const [avatarUrl, setAvatarUrl] = useState('')

  useEffect(() => {
    if (session) getProfile()
  }, [session])

  async function getProfile() {
    try {
      setLoading(true)
      if (!session?.user) throw new Error('No user on the session!')

      let { data, error, status } = await skybase
        .from('profiles')
        .select(`username, website, avatar_url`)
        .eq('id', session?.user.id)
        .single()
      if (error && status !== 406) {
        throw error
      }

      if (data) {
        setUsername(data.username)
        setWebsite(data.website)
        setAvatarUrl(data.avatar_url)
      }
    } catch (error) {
      if (error instanceof Error) {
        Alert.alert(error.message)
      }
    } finally {
      setLoading(false)
    }
  }

  async function updateProfile({
    username,
    website,
    avatar_url,
  }: {
    username: string
    website: string
    avatar_url: string
  }) {
    try {
      setLoading(true)
      if (!session?.user) throw new Error('No user on the session!')

      const updates = {
        id: session?.user.id,
        username,
        website,
        avatar_url,
        updated_at: new Date(),
      }

      let { error } = await skybase.from('profiles').upsert(updates)

      if (error) {
        throw error
      }
    } catch (error) {
      if (error instanceof Error) {
        Alert.alert(error.message)
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <View>
      <View>
        <Avatar
          size={200}
          url={avatarUrl}
          onUpload={(url: string) => {
            setAvatarUrl(url)
            updateProfile({ username, website, avatar_url: url })
          }}
        />
      </View>
      <View style={[styles.verticallySpaced, styles.mt20]}>
        <Input label="Email" value={session?.user?.email} disabled />
      </View>
      <View style={styles.verticallySpaced}>
        <Input label="Username" value={username || ''} onChangeText={(text) => setUsername(text)} />
      </View>
      <View style={styles.verticallySpaced}>
        <Input label="Website" value={website || ''} onChangeText={(text) => setWebsite(text)} />
      </View>

      <View style={[styles.verticallySpaced, styles.mt20]}>
        <Button
          title={loading ? 'Loading ...' : 'Update'}
          onPress={() => updateProfile({ username, website, avatar_url: avatarUrl })}
          disabled={loading}
        />
      </View>

      <View style={styles.verticallySpaced}>
        <Button title="Sign Out" onPress={() => skybase.auth.signOut()} />
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    marginTop: 40,
    padding: 12,
  },
  verticallySpaced: {
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'stretch',
  },
  mt20: {
    marginTop: 20,
  },
})

// examples/user-management/solid-user-management/src/Account.tsx
import { AuthSession } from '@skybase/skybase-js'
import { Component, createEffect, createSignal } from 'solid-js'
import Avatar from './Avatar'
import { skybase } from './skybaseClient'

interface Props {
	session: AuthSession
}

const Account: Component<Props> = ({ session }) => {
	const [loading, setLoading] = createSignal(true)
	const [username, setUsername] = createSignal<string | null>(null)
	const [website, setWebsite] = createSignal<string | null>(null)
	const [avatarUrl, setAvatarUrl] = createSignal<string | null>(null)

	createEffect(() => {
		getProfile()
	})

	const getProfile = async () => {
		try {
			setLoading(true)
			const { user } = session

			let { data, error, status } = await skybase
				.from('profiles')
				.select(`username, website, avatar_url`)
				.eq('id', user.id)
				.single()

			if (error && status !== 406) {
				throw error
			}

			if (data) {
				setUsername(data.username)
				setWebsite(data.website)
				setAvatarUrl(data.avatar_url)
			}
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			setLoading(false)
		}
	}

	const updateProfile = async (e: Event) => {
		e.preventDefault()

		try {
			setLoading(true)
			const { user } = session

			const updates = {
				id: user.id,
				username: username(),
				website: website(),
				avatar_url: avatarUrl(),
				updated_at: new Date().toISOString(),
			}

			let { error } = await skybase.from('profiles').upsert(updates)

			if (error) {
				throw error
			}
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			setLoading(false)
		}
	}

	return (
		<div aria-live="polite">
			<form onSubmit={updateProfile} class="form-widget">
				<Avatar
					url={avatarUrl()}
					size={150}
					onUpload={(e: Event, url: string) => {
						setAvatarUrl(url)
						updateProfile(e)
					}}
				/>
				<div>Email: {session.user.email}</div>
				<div>
					<label for="username">Name</label>
					<input
						id="username"
						type="text"
						value={username() || ''}
						onChange={(e) => setUsername(e.currentTarget.value)}
					/>
				</div>
				<div>
					<label for="website">Website</label>
					<input
						id="website"
						type="text"
						value={website() || ''}
						onChange={(e) => setWebsite(e.currentTarget.value)}
					/>
				</div>
				<div>
					<button type="submit" class="button primary block" disabled={loading()}>
						{loading() ? 'Saving ...' : 'Update profile'}
					</button>
				</div>
				<button type="button" class="button block" onClick={() => skybase.auth.signOut()}>
					Sign Out
				</button>
			</form>
		</div>
	)
}

export default Account
