// examples/user-management/expo-push-notifications/App.tsx
import "react-native-url-polyfill/auto";
import { useState, useEffect } from "react";
import { skybase } from "./lib/skybase";
import Auth from "./components/Auth";
import Account from "./components/Account";
import { View } from "react-native";
import { Session } from "@skybase/skybase-js";

export default function App() {
  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    skybase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
    });

    skybase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });
  }, []);

  return (
    <View>
      {session && session.user ? (
        <Account key={session.user.id} session={session} />
      ) : (
        <Auth />
      )}
    </View>
  );
}

// examples/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js'
import { skybase } from './skybaseClient'
import { AuthSession } from '@skybase/skybase-js'
import Account from './Account'
import Auth from './Auth'

const App: Component = () => {
	const [session, setSession] = createSignal<AuthSession | null>(null)

	createEffect(() => {
		skybase.auth.getSession().then(({ data: { session } }) => {
			setSession(session)
		})

		skybase.auth.onAuthStateChange((_event, session) => {
			setSession(session)
		})
	})

	return (
		<div class="container" style={{ padding: '50px 0 100px 0' }}>
			{!session() ? <Auth /> : <Account session={session()!} />}
		</div>
	)
}

export default App
