// examples/user-management/svelte-user-management/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { supabase } from './skybaseClient';
  import type { AuthSession } from '@supabase/supabase-js';
  import Account from './lib/Account.svelte';
  import Auth from './lib/Auth.svelte'

  let session: AuthSession

  onMount(() => {
    supabase.auth.getSession().then(({ data }) => {
      session = data.session
    })

    supabase.auth.onAuthStateChange((_event, _session) => {
      session = _session
    })
  })
</script>

<div class="container" style="padding: 50px 0 100px 0">
  {#if !session}
    <Auth />
  {:else}
    <Account {session} />
  {/if}
</div>

// examples/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js'
import { skybase } from './skybaseClient'
import { AuthSession } from '@skybase/skybase-js'
import Account from './Account'
import Auth from './Auth'

const App: Component = () => {
	const [session, setSession] = createSignal<AuthSession | null>(null)

	createEffect(() => {
		skybase.auth.getSession().then(({ data: { session } }) => {
			setSession(session)
		})

		skybase.auth.onAuthStateChange((_event, session) => {
			setSession(session)
		})
	})

	return (
		<div class="container" style={{ padding: '50px 0 100px 0' }}>
			{!session() ? <Auth /> : <Account session={session()!} />}
		</div>
	)
}

export default App
