// examples/user-management/nextjs-user-management/app/account/avatar.tsx
'use client'
import React, { useEffect, useState } from 'react'
import { createClient } from '@/utils/skybase/client'
import Image from 'next/image'

export default function Avatar({
  uid,
  url,
  size,
  onUpload,
}: {
  uid: string | null
  url: string | null
  size: number
  onUpload: (url: string) => void
}) {
  const skybase = createClient()
  const [avatarUrl, setAvatarUrl] = useState<string | null>(url)
  const [uploading, setUploading] = useState(false)

  useEffect(() => {
    async function downloadImage(path: string) {
      try {
        const { data, error } = await skybase.storage.from('avatars').download(path)
        if (error) {
          throw error
        }

        const url = URL.createObjectURL(data)
        setAvatarUrl(url)
      } catch (error) {
        console.log('Error downloading image: ', error)
      }
    }

    if (url) downloadImage(url)
  }, [url, skybase])

  const uploadAvatar: React.ChangeEventHandler<HTMLInputElement> = async (event) => {
    try {
      setUploading(true)

      if (!event.target.files || event.target.files.length === 0) {
        throw new Error('You must select an image to upload.')
      }

      const file = event.target.files[0]
      const fileExt = file.name.split('.').pop()
      const filePath = `${uid}-${Math.random()}.${fileExt}`

      const { error: uploadError } = await skybase.storage.from('avatars').upload(filePath, file)

      if (uploadError) {
        throw uploadError
      }

      onUpload(filePath)
    } catch (error) {
      alert('Error uploading avatar!')
    } finally {
      setUploading(false)
    }
  }

  return (
    <div>
      {avatarUrl ? (
        <Image
          width={size}
          height={size}
          src={avatarUrl}
          alt="Avatar"
          className="avatar image"
          style={{ height: size, width: size }}
        />
      ) : (
        <div className="avatar no-image" style={{ height: size, width: size }} />
      )}
      <div style={{ width: size }}>
        <label className="button primary block" htmlFor="single">
          {uploading ? 'Uploading ...' : 'Upload'}
        </label>
        <input
          style={{
            visibility: 'hidden',
            position: 'absolute',
          }}
          type="file"
          id="single"
          accept="image/*"
          onChange={uploadAvatar}
          disabled={uploading}
        />
      </div>
    </div>
  )
}

// examples/user-management/solid-user-management/src/Avatar.tsx
import { Component, createEffect, createSignal, JSX } from 'solid-js'
import { skybase } from './skybaseClient'

interface Props {
	size: number
	url: string | null
	onUpload: (event: Event, filePath: string) => void
}

const Avatar: Component<Props> = (props) => {
	const [avatarUrl, setAvatarUrl] = createSignal<string | null>(null)
	const [uploading, setUploading] = createSignal(false)

	createEffect(() => {
		if (props.url) downloadImage(props.url)
	})

	const downloadImage = async (path: string) => {
		try {
			const { data, error } = await skybase.storage.from('avatars').download(path)
			if (error) {
				throw error
			}
			const url = URL.createObjectURL(data)
			setAvatarUrl(url)
		} catch (error) {
			if (error instanceof Error) {
				console.log('Error downloading image: ', error.message)
			}
		}
	}

	const uploadAvatar: JSX.EventHandler<HTMLInputElement, Event> = async (event) => {
		try {
			setUploading(true)

			const target = event.currentTarget
			if (!target?.files || target.files.length === 0) {
				throw new Error('You must select an image to upload.')
			}

			const file = target.files[0]
			const fileExt = file.name.split('.').pop()
			const fileName = `${Math.random()}.${fileExt}`
			const filePath = `${fileName}`

			let { error: uploadError } = await skybase.storage.from('avatars').upload(filePath, file)

			if (uploadError) {
				throw uploadError
			}

			props.onUpload(event, filePath)
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			setUploading(false)
		}
	}

	return (
		<div style={{ width: `${props.size}px` }} aria-live="polite">
			{avatarUrl() ? (
				<img
					src={avatarUrl()!}
					alt={avatarUrl() ? 'Avatar' : 'No image'}
					class="avatar image"
					style={{ height: `${props.size}px`, width: `${props.size}px` }}
				/>
			) : (
				<div
					class="avatar no-image"
					style={{ height: `${props.size}px`, width: `${props.size}px` }}
				/>
			)}
			<div style={{ width: `${props.size}px` }}>
				<label class="button primary block" for="single">
					{uploading() ? 'Uploading ...' : 'Upload avatar'}
				</label>
				<span style="display:none">
					<input
						type="file"
						id="single"
						accept="image/*"
						onChange={uploadAvatar}
						disabled={uploading()}
					/>
				</span>
			</div>
		</div>
	)
}

export default Avatar
